
services:
  mlflow:
    build: ./
    container_name: mlflow
    ports:
      - "5000:5000"
    environment:
      - BACKEND_STORE_URI=${BACKEND_STORE_URI}
      - ARTIFACT_STORE=${ARTIFACT_STORE}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./src/mlflow/mlruns:/mlflow/mlruns