include:
  - ../../../mlflow/docker-compose.yml

services:
  model-optimizer:
    build:
      context: ../../../
      dockerfile: DataAnalysis/predictive/PredictiveEngine/ModelOptimizer/Dockerfile
      
volumes:
  shared-volume: